name: "sfme settings file"
version: "0.0.1"

api_id: ""
api_hash: ""

proxy:
  socks5:
  http:
  mtp:

redis:
  host: "127.0.0.1"
  port: "6379"
  password: "123456"

plugins:
  unconditional_forwarding:
    enable: false
    rules:
      "-1001555555556": "-1001555555555"