name: "sfme settings file"
version: "0.0.1"

api_id: ""
api_hash: ""

proxy:
  enable: false
  scheme: "socks5"  # "socks4", "socks5" and "http" are supported
  hostname: "127.0.0.1"
  port: 6153
  username: ""
  password: ""

redis:
  host: "127.0.0.1"
  port: "6379"
  password: "123456"

plugins:
  unconditional_forwarding:
    enable: false
    rules:
      "-1001555555556": "-1001555555555"
  whitelist_of_stranger:
    enable: false
    deal: archive # 处理方式 delete/archive